# Generated by Django 5.0.9 on 2026-08-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presencia", "0014_controlassistencia_notificacions_familia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="impartir",
            name="estat_neteja_aula",
            field=models.CharField(
                blank=True,
                choices=[
                    ("N", "Aula neta"),
                    ("A", "Aula acceptable"),
                    ("B", "Aula bruta"),
                ],
                default=None,
                max_length=1,
                null=True,
            ),
        ),
    ]
