# Generated by Django 5.1.15 on 2026-07-26 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnes", "0024_remove_alumne_usuaris_app_associats"),
        ("horaris", "0005_auto_20191009_1056"),
        ("incidencies", "0009_expulsio_notificacions_familia_and_more"),
        ("usuaris", "0014_delete_qrportal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expulsio",
            options={
                "verbose_name": "Falta greu",
                "verbose_name_plural": "Faltes greus",
            },
        ),
        migrations.AlterField(
            model_name="expulsio",
            name="alumne",
            field=models.ForeignKey(
                help_text="Alumne al qual s'aplica la falta greu",
                on_delete=django.db.models.deletion.CASCADE,
                to="alumnes.alumne",
            ),
        ),
        migrations.AlterField(
            model_name="expulsio",
            name="dia_expulsio",
            field=models.DateField(
                blank=True, help_text="Dia en que l'alumne ha rebut la falta greu"
            ),
        ),
        migrations.AlterField(
            model_name="expulsio",
            name="franja_expulsio",
            field=models.ForeignKey(
                help_text="Franja en que s'ha registrat la falta greu",
                on_delete=django.db.models.deletion.CASCADE,
                to="horaris.franjahoraria",
            ),
        ),
        migrations.AlterField(
            model_name="expulsio",
            name="moment_comunicacio_a_tutors",
            field=models.DateTimeField(
                blank=True,
                help_text="Moment en que aquesta falta greu ha estat comunicada als tutors",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="expulsio",
            name="motiu",
            field=models.TextField(
                help_text="Motiu de la falta greu. Aquesta informació la rebran els pares. No posar dades metges ni de salut."
            ),
        ),
        migrations.AlterField(
            model_name="expulsio",
            name="professor",
            field=models.ForeignKey(
                blank=True,
                help_text="Professor que aplica la falta greu",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="usuaris.professor",
            ),
        ),
        migrations.AlterField(
            model_name="expulsio",
            name="professor_recull",
            field=models.ForeignKey(
                help_text="Professor que recull la falta greu",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expulsions_recollides",
                to="usuaris.professor",
            ),
        ),
        migrations.AlterField(
            model_name="expulsio",
            name="tramitacio_finalitzada",
            field=models.BooleanField(
                default=False,
                help_text="Marca aquesta cassella quan hagis finalitzat tota la tramitació de la falta greu. Un cop tramitada no es pot esborrar ni modificar.",
            ),
        ),
        migrations.AlterField(
            model_name="sancio",
            name="data_fi",
            field=models.DateField(help_text="Darrer dia de falta greu"),
        ),
    ]
